seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see gaussian_model parameters
    class: GaussianMixin
    clip_actions: True
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network_log_prob: True
    network:
      - name: net
        input: STATES
        layers:
          - hyper_embedder:
              hidden_dim: 128
          - hyper_lerp:
              hidden_dim: 128
          - hyper_normal:
              hidden_dim: 128
              out_dim: ACTIONS
          - tanh_normal_squasher:
              min_log_std: -20.0
              max_log_std: 2.0
  critic_1:  # see deterministic_model parameters
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES_ACTIONS
        layers:
          - hyper_embedder:
              hidden_dim: 256
          - hyper_lerp:
              hidden_dim: 256
          - hyper_linear:
              hidden_dim: 256
              out_dim: 101
  critic_2:  critic_1
  target_critic_1:  critic_1
  target_critic_2:  critic_1

# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: 15625


# https://skrl.readthedocs.io/en/latest/api/agents/ppo.html
agent:
  class: SIMBA_V2
  discount_factor: 0.98
  batch_size: 4096
  gradient_steps: 1
  polyak: 0.005
  random_timesteps: 0
  learning_starts: 10000
  learn_entropy: True
  initial_entropy_value: 0.01
  actor_learning_rate: 0.0007
  critic_learning_rate: 0.0007
  entropy_learning_rate: 0.0007
  normalize_weights: True
  use_categorical_critic: True
  min_v: -5.0
  max_v: 5.0
  num_bins: 101

  state_preprocessor: simba.TorchRunningMeanStd
  experiment:
    directory: ""
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  timesteps: 200000
  environment_info: log
