x-default-isaac-lab-playground-environment: &default-isaac-lab-playground-environment
  - OMNI_KIT_ALLOW_ROOT=1
  - DISPLAY=:0
  - TERM=xterm-256color
  - SHELL=zsh
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US:en
  - LC_ALL=en_US.UTF-8

x-default-isaac-lab-playground-deploy: &default-isaac-lab-playground-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  isaac-lab-playground:
    env_file: .env.base
    image: nvcr.io/nvidia/isaac-sim:4.5.0
    # build:
    #   context: ../
    #   dockerfile: docker/Dockerfile
    #   args:
    #     - ISAACLAB_BASE_IMAGE_ARG=isaac-lab-base
    #     - DOCKER_ISAACLAB_EXTENSION_playground_PATH_ARG=/workspace/foobarbaz
    # image: isaac-lab-playground
    container_name: isaac-lab-playground
    volumes:
      - type: bind
        source: ../
        target: /home/ubuntu/isaac-lab-playground
    network_mode: host
    environment: *default-isaac-lab-playground-environment
    deploy: *default-isaac-lab-playground-deploy
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true
